"""empty message

Revision ID: fe76d4997809
Revises: 
Create Date: 2020-07-18 15:27:35.455034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe76d4997809'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'book', ['id'])
    op.create_unique_constraint(None, 'encyclopedia', ['id'])
    op.create_unique_constraint(None, 'moment', ['id'])
    op.create_unique_constraint(None, 'plant', ['id'])
    op.add_column('user', sa.Column('_password', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', '_password')
    op.drop_constraint(None, 'plant', type_='unique')
    op.drop_constraint(None, 'moment', type_='unique')
    op.drop_constraint(None, 'encyclopedia', type_='unique')
    op.drop_constraint(None, 'book', type_='unique')
    # ### end Alembic commands ###
